name: retail_vision_tracker
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip>=23.0
  - setuptools>=65.5.1
  - numpy>=1.20.0
  - pandas>=1.3.0
  - matplotlib>=3.5.0
  - seaborn>=0.12.0
  - pip:
    - streamlit>=1.15.0
    - opencv-python-headless>=4.5.0
    - requests>=2.25.0
    - tqdm>=4.50.0
    - pillow>=9.0.0
    - torch>=2.2.0
    - torchvision>=0.17.0
    - ultralytics>=8.0.0 